export const constants = [
    {
        image:"Background",
        layer:0,
        id:"bg-image",
        list: [
         {
            image:"blue50",
            url:`\\alpaca\\backgrounds\\blue50.png`,
            id:"bg-image",
          },
         {
            image:"blue60",
            url:`\\alpaca\\backgrounds\\blue60.png`,
            id:"bg-image",
          },
         {
            image:"blue70",
            url:`\\alpaca\\backgrounds\\blue70.png`,
            id:"bg-image",
          },
         {
            image:"darkblue30",
            url:`\\alpaca\\backgrounds\\darkblue30.png`,
            id:"bg-image",
          },
         {
            image:"darkblue50",
            url:`\\alpaca\\backgrounds\\darkblue50.png`,
            id:"bg-image",
          },
         {
            image:"darkblue70",
            url:`\\alpaca\\backgrounds\\darkblue70.png`,
            id:"bg-image",
          },
         {
            image:"green50",
            url:`\\alpaca\\backgrounds\\green50.png`,
            id:"bg-image",
          },
         {
            image:"green60",
            url:`\\alpaca\\backgrounds\\green60.png`,
            id:"bg-image",
          },
         {
            image:"green70",
            url:`\\alpaca\\backgrounds\\green70.png`,
            id:"bg-image",
          },
         {
            image:"grey40",
            url:`\\alpaca\\backgrounds\\grey40.png`,
            id:"bg-image",
          },
         {
            image:"grey70",
            url:`\\alpaca\\backgrounds\\grey70.png`,
            id:"bg-image",
          },
         {
            image:"grey80",
            url:`\\alpaca\\backgrounds\\grey80.png`,
            id:"bg-image",
          },
         
         {
            image:"red50",
            url:`\\alpaca\\backgrounds\\red50.png`,
            id:"bg-image",
          },
         {
            image:"red60",
            url:`\\alpaca\\backgrounds\\red60.png`,
            id:"bg-image",
          },
         {
            image:"red70",
            url:`\\alpaca\\backgrounds\\red70.png`,
            id:"bg-image",
          },
         
         {
            image:"yellow50",
            url:`\\alpaca\\backgrounds\\yellow50.png`,
            id:"bg-image",
          },
         {
            image:"yellow60",
            url:`\\alpaca\\backgrounds\\yellow60.png`,
            id:"bg-image",
          },
         {
            image:"yellow70",
            url:`\\alpaca\\backgrounds\\yellow70.png`,
            id:"bg-image",
          },
         
       ]
    },
    
    {
        image:"Ear",
        layer:5,
        id:"ear-image",
        list: [
         {
            image:"default",
            url:`\\alpaca\\ears\\default.png`,
            id:"ear-image",
          },
         {
            image:"tilt-backward",
            url:`\\alpaca\\ears\\tilt-backward.png`,
            id:"ear-image",
          },
         {
            image:"tilt-forward",
            url:`\\alpaca\\ears\\tilt-forward.png`,
            id:"ear-image",
          },
       ]
    },

    {
        image:"Hair",
        layer:7,
        id:"hair-image",
        list: [
         {
            image:"default",
            url:`\\alpaca\\hair\\default.png`,
            id:"hair-image",
          },
         {
            image:"bang",
            url:`\\alpaca\\hair\\bang.png`,
            id:"hair-image",
          },
         {
            image:"curls",
            url:`\\alpaca\\hair\\curls.png`,
            id:"hair-image",
          },
         {
            image:"elegant",
            url:`\\alpaca\\hair\\elegant.png`,
            id:"hair-image",
          },
         {
            image:"fancy",
            url:`\\alpaca\\hair\\fancy.png`,
            id:"hair-image",
          },
         {
            image:"quiff",
            url:`\\alpaca\\hair\\quiff.png`,
            id:"hair-image",
          },
         {
            image:"short",
            url:`\\alpaca\\hair\\short.png`,
            id:"hair-image",
          },
       ]
    },

    {
        image:"Leg",
        layer:5,
        id:"leg-image",
        list: [
         {
            image:"default",
            url:`\\alpaca\\leg\\default.png`,
            id:"leg-image",
          },
         {
            image:"bubble-tea",
            url:`\\alpaca\\leg\\bubble-tea.png`,
            id:"leg-image",
          },
         {
            image:"game-console",
            url:`\\alpaca\\leg\\game-console.png`,
            id:"leg-image",
          },
         {
            image:"tilt-backward",
            url:`\\alpaca\\leg\\tilt-backward.png`,
            id:"leg-image",
          },
         {
            image:"tilt-forward",
            url:`\\alpaca\\leg\\tilt-forward.png`,
            id:"leg-image",
          },
         {
            image:"cookie",
            url:`\\alpaca\\leg\\cookie.png`,
            id:"leg-image",
          }
       ]
    },
 
     {
         image:"Eyes",
         layer:10,
         id:"eyes-image",
         list: [
             {
                 image:"default",
                 url:"\\alpaca\\eyes\\default.png",
                 id:"eyes-image",
             },
             {
                 image:"angry",
                 url:"\\alpaca\\eyes\\angry.png",
                 id:"eyes-image",
             },
             {
                 image:"naughty",
                 url:"\\alpaca\\eyes\\naughty.png",
                 id:"eyes-image",
             },
             {
                 image:"panda",
                 url:"\\alpaca\\eyes\\panda.png",
                 id:"eyes-image",
             },
             {
                 image:"smart",
                 url:"\\alpaca\\eyes\\smart.png",
                 id:"eyes-image",
             },
             
             {
                 image:"star",
                 url:"\\alpaca\\eyes\\star.png",
                 id:"eyes-image",
             },
         ]
        },
             
     {
         image:"Mouth",
         layer:15,
         id:"mouth-image",
         list: [
             {
                 image:"default",
                 url:"\\alpaca\\mouth\\default.png",
                 id:"mouth-image",
             },
             {
                 image:"astonished",
                 url:"\\alpaca\\mouth\\astonished.png",
                 id:"mouth-image",
             },
             {
                 image:"eating",
                 url:"\\alpaca\\mouth\\eating.png",
                 id:"mouth-image",
             },
             {
                 image:"laugh",
                 url:"\\alpaca\\mouth\\laugh.png",
                 id:"mouth-image",
             },
             {
                 image:"tongue",
                 url:"\\alpaca\\mouth\\tongue.png",
                 id:"mouth-image",
             },
              ]
           },
 
         {
         image:"Neck",
         layer:5,
         id:"neck-image",
         list: [
             {
                 image:"default",
                 url:"\\alpaca\\neck\\default.png",
                 id:"neck-image",
             },
             {
                 image:"bend-backward",
                 url:"\\alpaca\\neck\\bend-backward.png",
                 id:"neck-image",
             },
             {
                 image:"bend-forward",
                 url:"\\alpaca\\neck\\bend-forward.png",
                 id:"neck-image",
             },
             {
                 image:"thick",
                 url:"\\alpaca\\neck\\thick.png",
                 id:"neck-image",
             },
              ]
           },
 
           {
            image:"Accessories",
            layer:20,
            list: [
             {
                image:"earings",
                url:`\\alpaca\\accessories\\earings.png`,
                id:"earings-image",
                layer:13
              },
             {
                image:"flower",
                url:`\\alpaca\\accessories\\flower.png`,
                id:"flower-image",
                layer:14
              },
             {
                image:"glasses",
                url:`\\alpaca\\accessories\\glasses.png`,
                id:"glasses-image",
                layer:12
              },
             {
                image:"headphone",
                url:`\\alpaca\\accessories\\headphone.png`,
                id:"headphone-image",
                layer:9
              },
           ]
        },

        {
         image:"Nose",
         layer:10,
         id:"nose-image",
         list:[
            {image:"nose",
            url:`\\alpaca\\nose.png`,
            id:"nose-image",
            layer:10}

         ]
        }
 ]